style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/RobinThrift/hkit
options:
  commits:
    filters:
      Type:
       - Add
       - Fix
       - Refactor
  commit_groups:
    title_maps:
      Add: Features
      Fix: Fixes
      Refactor: Refactoring
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE
