name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go 1.21
      uses: actions/setup-go@v3
      with:
        go-version: ^1.21
    - name: Install just 1.14.0
      uses: kodeshack/action-install-gh-release@v1.3.0
      with:
        owner: casey
        repo: just
        version: '1.14.0'
        test: just --version
    - name: Generate SBOM
      run: |
        just sbom
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        allowUpdates: true
        artifacts: "sbom.json"
